reactiveWebGL <- function (outputId) 
{
  HTML(paste("<div id=\"", outputId, "\" class=\"shiny-webgl-output\"></div>", sep=""))
}

choices <- c("WM", "GM", "Lesion")
vec <- c("red", "green", "blue")
names(vec) <- choices

shinyUI(pageWithSidebar(    
  headerPanel("WebGL Demo"),
  
  sidebarPanel(
    selectInput("dataset", "Choose a dataset:", 
                choices = c("scan1", "scan2")),    
    checkboxInput(inputId= choices[1], label= choices[1], value=TRUE),
    checkboxInput(inputId= choices[2], label= choices[2], value=TRUE),
    checkboxInput(inputId= choices[3], label= choices[3], value=TRUE)
  ),    
  
  mainPanel(        
    verbatimTextOutput("view"),
    
    #Add our custom JS script which binds the custom WebGL type (just HTML)
    tags$head(tags$script(src="rgl.js", type="text/javascript")),
    #Add CanvasMatrix (needed for the WebGL generated by rgl)
    tags$head(tags$script(src="CanvasMatrix.js", type="text/javascript")),
    
    reactiveWebGL(outputId = "webGL")  
  )
))
